package net.hrcautomation.jobobserver;

enum FaultReason {
    REQUEST_ID_REUSED,
    REQUEST_CAPACITY_EXCEEDED,
    JOB_CAPACITY_EXCEEDED,
    ARM_DEADLINE_EXPIRED,
    EVENT_BEFORE_ARM,
    UNEXPECTED_RELEVANT_JOB,
    JOB_MISMATCH,
    DUPLICATE_SCHEDULED,
    LIFECYCLE_BEFORE_SCHEDULED,
    CALLBACK_TIME_REGRESSED,
    JOB_DESCRIPTOR_CHANGED,
    DUPLICATE_RUNNING,
    DONE_BEFORE_RUNNING,
    DUPLICATE_DONE,
    MISSING_TERMINAL_STATUS,
    UNKNOWN_TERMINAL_STATUS,
    TERMINAL_EVENT_REJECTED,
    STATUS_PLUGIN_OMITTED,
    JOB_ID_EXHAUSTED,
    EVENT_EMISSION_FAILURE
}
